services:
    database:
        image: mongo:4.4
        container_name: mentor-comentarios
        ports: 
            - "27017:27017"
        environment:
            MONGO_INITDB_DATABASE: dbmessages